3360 loan simulator
lita-co/loan-creator-web pull request #2
Opened 2021-07-20 15:36 UTC by louiseponton

Test d'affichage: ajout d'un chart dans la visualisation du simulateur de prêt

https://trello.com/c/LALld6AO/3319-process-accueil-de-louise

2021-07-22 13:47 UTC, louiseponton commented on lib/loan_creator_web/views/table_row.erb
> -  <td><%= number_to_euro(term.due_interests_end_of_period) %></td>
A été enlevé du tableau car non utilisé dans le chart et nécessitais l'update de loan-creator dans notre app, qui sera seulement traité avec https://trello.com/c/Bz3F8QjW/3286-refacto-transaction-de-g%C3%A9n%C3%A9ration-des-%C3%A9ch%C3%A9ances

2021-07-22 15:10 UTC, sherpanat commented
Tu ne voulais pas cibler `staging` d'abord ?

2021-07-23 08:15 UTC, louiseponton commented
> Tu ne voulais pas cibler staging d'abord ?

La comme c'est un nouveau repo du gem capsens et qu'on l'utilise dans Lita.co avec le lien github, je ne pensais pas nécessaire d'introduire une branche staging avant master (pas de déploiement prévu sur staging ou master de la modif). Mais peut etre que je ne vois pas l'avantage d'avoir la branche staging ici parce que je ne suis pas assez familière avec le process de MEP (?) A toi de me dire :)

2021-07-23 16:11 UTC, GuillaumeLegendre requested changes

2021-07-23 16:11 UTC, GuillaumeLegendre commented on lib/loan_creator_web/views/chart.erb
> +var ctx = document.getElementById('myChart').getContext('2d');
Est ce que tu peux conserver la même indentation que les autres fichier. Donc 2 espace. Et rajouter une indentation. à l'interieur de la balise script stp :)

2021-07-27 13:09 UTC, GuillaumeLegendre approved these changes

2021-07-27 13:09 UTC, merged